version: '2'
services:
  node1:
    environment:
      - PEERS=ws://node3:6001,ws://node2:6001,ws://node4:6001
      - SECRET_KEY=x]vf4yp0yf
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  node2:
    environment:
      - PEERS=ws://node1:6001,ws://node3:6001,ws://node4:6001
      - SECRET_KEY=x]vf4yp0yf
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3002:3001"
  node3:
    environment:
      - PEERS=ws://node1:6001,ws://node2:6001,ws://node4:6001
      - SECRET_KEY=x]vf4yp0yf
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3003:3001"
  node4:
    environment:
      - PEERS=ws://node1:6001,ws://node2:6001,ws://node3:6001
      - SECRET_KEY=x]vf4yp0yf
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3004:3001"
